### ISSUE TITLE
Day 36 Lab - Take Carthage out of top of .gitignore

### ISSUE THREAD

**Issue by elaewin** [luayyounus/LocationReminders#3]
The problematic part of the file is 

```
### Carthage ###
# Carthage - A simple, decentralized dependency manager for Cocoa
Carthage/Checkouts/
Carthage/Build/
```

**Comment by elaewin** [comment]
Remember that you'll have to clear your local git cache and re-add all your files for the changed `.gitignore` to take effect.

**Comment by luyounus** [comment]
Fixed. Thank you Erica!
